// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $pinned_path_ from "./routes/pinned/[path].tsx";
import * as $pinned_index from "./routes/pinned/index.tsx";
import * as $posts_path_ from "./routes/posts/[path].tsx";
import * as $posts_index from "./routes/posts/index.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
    "./routes/pinned/[path].tsx": $pinned_path_,
    "./routes/pinned/index.tsx": $pinned_index,
    "./routes/posts/[path].tsx": $posts_path_,
    "./routes/posts/index.tsx": $posts_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
