apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o release/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: blog
  name: blog
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: blog
