apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o release/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: blog
  name: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: blog
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o release/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: blog
    spec:
      containers:
        - env:
            - name: BLOG_PROVIDER_HOST
              valueFrom:
                configMapKeyRef:
                  key: BLOG_PROVIDER_HOST
                  name: blog-env
          image: ghcr.io/frixxie/simple_blog:0.1.1
          name: blog
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
